### ISSUE TITLE
Allow nickname via nordvpn mesh set nickname

### ISSUE THREAD

**Issue by tchar** [MattsTechInfo/Meshnet#20]
Hello,

Nice work!

Would it be possible to support the command `nordvpn mesh set nickname`? I could make a PR for this if you want.

**Comment by MattsBos** [comment]
Hi tchar.

Thanks!
I haven't really looked at the nickname part yet, but I guess it can be implemented just like the current permission ENVs right?

If so, that would be an easy addition. Only thing that would need to be verified is what happens if you run the command again at reboot, if it errors or just says "Nickname is already present" like the current permission commands.

**Comment by MattsBos** [comment]
I've just pushed and added the nickname support to the latest release. #21
